#Swagger docs:
#https://swagger.io/docs/specification/basic-structure/
openapi: 3.0.0
info:
  title: My Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.1
servers:
  - url: http://localhost:3000/v1
    description: API server
paths:
  /api:
    get:
      summary: Returns msg.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: Some description
          content:
            application/json:
              schema:
                type: object
                properties:
                  type: msg
    post:
      summary: Returns msg.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                value:
                  type: integer
                issuer:
                  type: string
              example:   # Sample object
                value: 10
                issuer: MagnetoCorp
      responses:
        '200':
          description: OK
