# https://docs.microsoft.com/en-us/azure/aks/concepts-storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: peer-storage
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
